[package]
name = "wstartpage"
version = "0.0.1"
authors = ["Adam JÄ™drzejowski <adam@jedrzejowski.pl>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
serde = "1.0.126"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
once_cell = "1.7.2"
